name: Dart IOUring Transport

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'

      - name: Cache VM
        uses: actions/cache@v3.0.5
        id: cache
        with:
          path: ./ubuntu-22.10-server-cloudimg-amd64.img
          key: ubuntu-22.10
      
      - name: Prepare runner
        run: sudo ./prepare.sh
      
      - name: Launch VM
        run: sudo ./install.sh

      - name: Run
        run: ./run.sh