name: Dart IOUring Transport

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'

      - name: Native configure
        run: cd binding && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .

      - name: Native build
        run: cd binding &&  make -j 

      - name: Dart dependencies
        run: cd dart && dart pub get

      - name: Run tests
        run: cd dart && dart run test/test.dart