name: Dart IOUring Transport
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Native configure
        run: cd native && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .

      - name: Native build
        run: cd native && make

      - name: Dart build
        run: cd dart && dart pub get && dart compile exe test/test.dart

      - name: Dart Test
        run: sudo bash -c "ulimit -l 65536 && ulimit -a && cd dart && test/test.exe"
