name: Dart IOUring Transport
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Native configure
        run: cd native && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .

      - name: Native build
        run: cd native &&  make -j

      - name: Dart build
        run: cd dart && dart pub get && dart compile exe test/test.dart

      - name: Dart Test
        run: cd dart && test/test.exe
