name: Dart IOUring Transport
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1

      - name: OS configure
        run: sudo cat >/etc/sysctl.conf <<EOL
          fs.file-max = 2097152
          vm.swappiness = 10
          vm.dirty_ratio = 60
          vm.dirty_background_ratio = 2
          kernel.sched_migration_cost_ns = 5000000
          net.ipv4.tcp_synack_retries = 2
          net.ipv4.ip_local_port_range = 2000 65535
          net.ipv4.tcp_rfc1337 = 1
          net.ipv4.tcp_syncookies = 1
          net.ipv4.tcp_fin_timeout = 15
          net.ipv4.tcp_keepalive_time = 300
          net.ipv4.tcp_keepalive_probes = 5
          net.ipv4.tcp_keepalive_intvl = 15
          net.core.rmem_default = 31457280
          net.core.rmem_max = 33554432
          net.core.wmem_default = 31457280
          net.core.wmem_max = 33554432
          net.core.somaxconn = 65535
          net.core.netdev_max_backlog = 65536
          net.core.optmem_max = 25165824
          net.ipv4.tcp_mem = 786432 1048576 26777216
          net.ipv4.udp_mem = 65536 131072 262144
          net.ipv4.tcp_rmem = 8192 87380 33554432
          net.ipv4.udp_rmem_min = 16384
          net.ipv4.tcp_wmem = 8192 65536 33554432
          net.ipv4.udp_wmem_min = 16384
          net.ipv4.tcp_max_tw_buckets = 1440000
          net.ipv4.tcp_tw_recycle = 1
          net.ipv4.tcp_tw_reuse = 1
          EOL && sudo sysctl -p

      - name: Native configure
        run: cd native && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .

      - name: Native build
        run: cd native && make

      - name: Dart build
        run: cd dart && dart pub get && dart compile exe test/test.dart

      - name: Dart Test
        run: sudo bash -c "ulimit -l 65536 && ulimit -a && cd dart && test/test.exe"
