name: Dart IOUring Transport
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Native build
        run: |
           rm -rf build || true
           mkdir build
           cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -B$(pwd)/build -S$(pwd)
           cd build && make -j

      - name: Dart build
        run: cd dart && dart pub get && dart compile exe test/test.dart

      - name: Dart Test
        run: |
          sudo env "PATH=$PATH" bash -c "ulimit -l 65536 && ulimit -a && cd dart && test/test.exe"